<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Uber_logo_2018.svg/1024px-Uber_logo_2018.svg.png" alt="UBER LOGO" width="50%" />

# UBER Pickups

# import libraries

In [1]:
import pandas as pd
import plotly.express as px

# Read data

In [2]:
zone = pd.read_csv('data/taxi-zone-lookup.csv')
print('Lines / Columns : ', zone.shape)

Lines / Columns :  (265, 3)

In [3]:
files = ["data/uber-trip-data/uber-raw-data-apr14.csv", "data/uber-trip-data/uber-raw-data-may14.csv", "data/uber-trip-data/uber-raw-data-jun14.csv", 'data/uber-trip-data/uber-raw-data-jul14.csv', 'data/uber-trip-data/uber-raw-data-aug14.csv', 'data/uber-trip-data/uber-raw-data-sep14.csv']

raw_2014 = pd.concat([pd.read_csv(f) for f in files], ignore_index=True)
print('Lines / Columns : ', raw_2014.shape)

Lines / Columns :  (4534327, 4)

In [4]:
raw_2015 = pd.read_csv('data/uber-raw-data-janjune-15.csv')
print('Lines / Columns : ', raw_2015.shape)

Lines / Columns :  (14270479, 4)

# Explore dataset

In [5]:
dataframes = [zone, raw_2014, raw_2015]
[print(f"Display of dataset: {display(df.head())}") for df in dataframes]

   LocationID        Borough                     Zone
0           1            EWR           Newark Airport
1           2         Queens              Jamaica Bay
2           3          Bronx  Allerton/Pelham Gardens
3           4      Manhattan            Alphabet City
4           5  Staten Island            Arden Heights

Display of dataset: None

          Date/Time      Lat      Lon    Base
0  4/1/2014 0:11:00  40.7690 -73.9549  B02512
1  4/1/2014 0:17:00  40.7267 -74.0345  B02512
2  4/1/2014 0:21:00  40.7316 -73.9873  B02512
3  4/1/2014 0:28:00  40.7588 -73.9776  B02512
4  4/1/2014 0:33:00  40.7594 -73.9722  B02512

Display of dataset: None

  Dispatching_base_num          Pickup_date Affiliated_base_num  locationID
0               B02617  2015-05-17 09:47:00              B02617         141
1               B02617  2015-05-17 09:47:00              B02617          65
2               B02617  2015-05-17 09:47:00              B02617         100
3               B02617  2015-05-17 09:47:00              B02774          80
4               B02617  2015-05-17 09:47:00              B02617          90

Display of dataset: None

[None, None, None]

We observe :
- date time MM/DD/YYYY
- lowercase and uppercase
- sorted raw data

In [6]:
# Basic stats
dataframes = {'zone':zone, 'raw_2014':raw_2014, 'raw_2015':raw_2015}

for name, df in dataframes.items():
    print()
    print('-------------------Dataframe : ', name, '-------------------')
    print(f"Rows :  \t {df.shape[0]}")
    print(f"Columns : \t {df.shape[1]}")

    print()
    print("Basics statistics: ")
    df_desc = df.describe(include='all') # numeric variables and catégorielles
    display(df_desc)

    print("Percentage of missing values")
    df_missing_values = df.isnull().sum()/df.shape[0]*100
    print(f"{name} : \n{df_missing_values}")
print('Done...')

-------------------Dataframe :  zone -------------------
Rows :  	 265
Columns : 	 3

Basics statistics:

        LocationID Borough                                           Zone
count   265.000000     265                                            265
unique         NaN       7                                            261
top            NaN  Queens  Governor's Island/Ellis Island/Liberty Island
freq           NaN      69                                              3
mean    133.000000     NaN                                            NaN
std      76.643112     NaN                                            NaN
min       1.000000     NaN                                            NaN
25%      67.000000     NaN                                            NaN
50%     133.000000     NaN                                            NaN
75%     199.000000     NaN                                            NaN
max     265.000000     NaN                                            NaN

Percentage of missing values
zone :
LocationID    0.0
Borough       0.0
Zone          0.0
dtype: float64

-------------------Dataframe :  raw_2014 -------------------
Rows :  	 4534327
Columns : 	 4

Basics statistics:

                Date/Time           Lat           Lon     Base
count             4534327  4.534327e+06  4.534327e+06  4534327
unique             260093           NaN           NaN        5
top     4/7/2014 20:21:00           NaN           NaN   B02617
freq                   97           NaN           NaN  1458853
mean                  NaN  4.073926e+01 -7.397302e+01      NaN
std                   NaN  3.994991e-02  5.726670e-02      NaN
min                   NaN  3.965690e+01 -7.492900e+01      NaN
25%                   NaN  4.072110e+01 -7.399650e+01      NaN
50%                   NaN  4.074220e+01 -7.398340e+01      NaN
75%                   NaN  4.076100e+01 -7.396530e+01      NaN
max                   NaN  4.211660e+01 -7.206660e+01      NaN

Percentage of missing values
raw_2014 :
Date/Time    0.0
Lat          0.0
Lon          0.0
Base         0.0
dtype: float64

-------------------Dataframe :  raw_2015 -------------------
Rows :  	 14270479
Columns : 	 4

Basics statistics:

,Dispatching_base_num,Pickup_date,Affiliated_base_num,locationID
count,14270479,14270479,14108284,1.427048e+07
unique,8,2744783,284,NaN
top,B02764,2015-06-27 22:19:00,B02764,NaN
freq,5753653,213,4352321,NaN
mean,NaN,NaN,NaN,1.520574e+02
std,NaN,NaN,NaN,7.159620e+01
min,NaN,NaN,NaN,1.000000e+00
25%,NaN,NaN,NaN,9.200000e+01
50%,NaN,NaN,NaN,1.570000e+02
75%,NaN,NaN,NaN,2.300000e+02
max,NaN,NaN,NaN,2.650000e+02

Percentage of missing values
raw_2015 :
Dispatching_base_num    0.000000
Pickup_date             0.000000
Affiliated_base_num     1.136577
locationID              0.000000
dtype: float64
Done...

We observe missing values on raw_2015

In [7]:
# Lowercase dataframes
for name, df in dataframes.items():
    df.columns = df.columns.str.lower() # lowercase columns names
    for col in df.select_dtypes(include=["object", 'str']).columns: # avoid warning for multi execution
        df[col] = df[col].str.lower()
        print()
    print('-------------------',name,'-------------------')
    print(df.head(1))
    for col in df.select_dtypes(include=["object", 'str']).columns: # avoid warning for multi execution
        df[col] = df[col].str.lower()
        print()
    print('-------------------',name,'-------------------')
    print(df.head(1))

TypeError: numpy string dtypes are not allowed, use 'str' or 'object' instead

In [ ]:
# raw_2014['base'].isin(raw_2015['dispatching_base_num']).value_counts()

On retrouve le nombre de lignes exact de raw_2014. Aucune base ne diffère des dispatching_base_num.

Pour s'en assurer, comparons les valeurs uniques.

In [ ]:
b14 = set(raw_2014['base'].unique())
b15_dispatch = set(raw_2015['dispatching_base_num'].unique())
b15_licence = set(raw_2015['affiliated_base_num'].unique())
print(len(b14), len(b15_dispatch), len(b15_licence), len(b14 & b15_dispatch & b15_licence))

# Treat datetime

In [ ]:
# import pandas as pd

# raw_2014["date/time"], raw_2015["pickup_date"] = [
#     pd.to_datetime(c, format=f) for c, f in [(raw_2014["date/time"], "%m/%d/%Y %H:%M:%S"),
#                                             (raw_2015["pickup_date"], "%Y-%m-%d %H:%M:%S")]
# ]

In [ ]:
cols = [raw_2014["date/time"], raw_2015["pickup_date"]]

converted = [pd.to_datetime(c, format=f) for c, f in zip(cols, ("%m/%d/%Y %H:%M:%S", "%Y-%m-%d %H:%M:%S")) # zip to use c and f together
]

raw_2014["date/time"], raw_2015["pickup_date"] = converted
print(raw_2014["date/time"].dtypes) # datetime64[ns]
print(raw_2015["pickup_date"].dtypes)
print([c.dtype for c in converted])  # # M8[ns]

# Fusionner raw_2015 et zone

In [ ]:
raw_2015 = raw_2015.merge(zone, on="locationid", how="left")

In [ ]:
raw_2015.head(1)

In [ ]:
raw_2015.to_csv("data/2015.csv", index=False)

# Treat missing values

Une position gps imputée fausserait les clusters. On supprime les lignes.

In [ ]:
before = raw_2015.shape[0]
raw_2015 = raw_2015.dropna(subset='affiliated_base_num') # drop lines where values are missing. 
missing_values = raw_2015.isnull().sum()/raw_2015.shape[0]*100
after = raw_2015.shape[0]
deleted_rows_pct = (before - after) / before * 100
print('deleted_rows_pct : ', deleted_rows_pct)
print(missing_values)

# Analyze one hour on one day

In [ ]:
raw_2015.head(1)

In [ ]:
raw_2014['date/time'].dtype

In [ ]:
raw_2015['pickup_date'].dtype

In [ ]:
begin = pd.Timestamp('2014-04-01 00:00:00')
end = begin + pd.Timedelta(hours=1)

t1 = raw_2014[(raw_2014['date/time'] >= begin) & (raw_2014['date/time'] < end)]

In [ ]:
t1

In [ ]:
bases_median = t1.groupby('base')[['lat', 'lon']].median().reset_index()

In [ ]:
print(bases_median)

In [ ]:
fig = px.scatter_map(t1, lat="lat", lon="lon", color="base", zoom=10, map_style="carto-positron")
fig.show()

Les bases b02617 et b02764 se superposent

# Create bases

In [ ]:
bases = raw_2014.groupby('base')[['lat', 'lon']].median().reset_index()

In [ ]:
raw_2014[['base', 'lon', 'lat']].to_csv("data/bases.csv", index=False)

In [ ]:
# print(bases)

# Search for duplicated values

In [ ]:
duplicated_values = bases[bases.duplicated(subset=["lat", "lon"], keep=False)]
print(duplicated_values.sort_values(['base', "lat", "lon"]))

In [ ]:
with pd.option_context("display.precision", 15):
    print(bases_median)

Les bases ont pratiquement les mêmes valeurs.

In [ ]:
# bases_t1 = bases_median.round({"lat": 4, "lon": 4})
# print(bases_t1[bases_t1.duplicated(subset=["lat", "lon"], keep=False)])

# Fusionner raw_2015 et bases

In [ ]:
raw_2015 = raw_2015.merge(bases[["base", "lon", "lat"]], left_on="dispatching_base_num", right_on="base", how="left").drop(columns="base")
print(raw_2015[["dispatching_base_num", "lon", "lat"]])
print(raw_2015[["lon", "lat"]])

In [ ]:
raw_2015.head(1)

# Detect outlyers

# Create sample

In [ ]:
mask = raw_2015[raw_2015['dispatching_base_num'].isin(bases_median['base'])]
n = 5000  # taille cible, choix provisoire
frac = n / len(mask)
sample = mask.groupby('dispatching_base_num').sample(frac=frac, random_state=42)
print(frac, len(sample))

In [ ]:
sample.to_csv("data/sample.csv", index=False)

Question : how use locationid